version: "3.5"

services:
  hugo:
    image: jojomi/hugo:latest
    volumes:
      - .:/src
    environment:
      - HUGO_WATCH=true
      - HUGO_REFRESH_TIME=3600
      - HUGO_THEME=hugo-theme-learn
      - HUGO_BASEURL=localhost
    restart: always
    ports: 
      - ${HUGO_PORT:-1313}:1313